#!/usr/bin/env python3
"""Generate docs/50-community/discussion-map.md — the whole forum on one page.

The FAQ harvester covers threads that have been *answered*. This covers all of
them, because a forum with sixty threads and no map is one where the third page
is never read: the useful thread you need is usually not the most recent one,
and GitHub's Discussions list offers no view that groups by purpose.

    python scripts/discussion_map.py            # write the file
    python scripts/discussion_map.py --check    # exit 1 if it is out of date
"""
from __future__ import annotations

import argparse
import json
import pathlib
import re
import subprocess
import sys

OWNER, REPO = "akash-coded", "nanorag"
OUT = pathlib.Path(__file__).resolve().parent.parent / "docs/50-community/discussion-map.md"

# Category order is reading order for someone arriving cold, not alphabetical.
ORDER = ["Announcements", "Q&A", "Show and tell", "Design Reviews",
         "Interview Prep", "Reading Club", "Ideas", "Polls", "General"]

# Within Q&A the prefixes are the real taxonomy, so they get their own sections.
PREFIX_GROUPS = [
    ("clinic",  re.compile(r"^\[clinic · "),  "Exercise clinic",
     "One long-running thread per exercise. Ask here rather than opening a duplicate."),
    ("lab",     re.compile(r"^\[lab · "),     "L.A.B. track threads",
     "One per track of the [L.A.B. simulator](../80-lab/README.md)."),
    ("maths",   re.compile(r"^\[maths\]"),    "Derivations",
     "Pairs with the derivations in "
     "[01-mathematical-foundations]"
     "(../30-learning/interview-prep/01-mathematical-foundations/README.md)."),
    ("errata",  re.compile(r"^\[errata\]"),   "Errata",
     "The material is wrong, or more confident than it should be. Confirmed errata become issues."),
]

QUERY = """
query($o:String!,$r:String!){
  repository(owner:$o,name:$r){
    discussions(first:100, orderBy:{field:CREATED_AT, direction:ASC}){
      nodes{
        number title url isAnswered
        category{ name }
        labels(first:10){ nodes{ name } }
        comments(first:60){ totalCount nodes{ replies(first:30){ totalCount } } } } } } }
"""


def fetch() -> list[dict]:
    proc = subprocess.run(
        ["gh", "api", "graphql", "-f", f"query={QUERY}", "-f", f"o={OWNER}", "-f", f"r={REPO}"],
        capture_output=True, text=True)
    if proc.returncode:
        sys.exit(f"gh failed: {proc.stderr.strip()}")
    return json.loads(proc.stdout)["data"]["repository"]["discussions"]["nodes"]


def depth(node: dict) -> int:
    replies = sum(c["replies"]["totalCount"] for c in node["comments"]["nodes"])
    return node["comments"]["totalCount"] + replies


def row(node: dict) -> str:
    mark = " ✅" if node.get("isAnswered") else ""
    n = depth(node)
    weight = "—" if n == 0 else ("●" * min(n // 3 + 1, 5))
    title = node["title"].replace("|", "\\|")
    return f"| [{title}]({node['url']}){mark} | {weight} {n} |"


def render(nodes: list[dict]) -> str:
    by_cat: dict[str, list[dict]] = {}
    for node in nodes:
        by_cat.setdefault(node["category"]["name"], []).append(node)

    answered = sum(1 for n in nodes if n.get("isAnswered"))
    comments = sum(depth(n) for n in nodes)
    out = [
        "# Discussion map",
        "",
        "Every thread, grouped by purpose. Generated by `scripts/discussion_map.py` and refreshed",
        "weekly — edit the thread, not this file.",
        "",
        f"**{len(nodes)} threads · {comments} comments · {answered} with a marked answer.**",
        "",
        "The **depth** column is comments plus nested replies. A thread with `—` is open and",
        "waiting for someone; that is an invitation, not a defect.",
        "",
        "New here? [The guide](discussions-guide.md) says where things go. If you want to",
        "contribute in fifteen minutes, the fastest useful thing is to reproduce a number in the",
        "docs and open an `[errata]` thread if it does not match.",
        "",
    ]

    for cat in ORDER:
        items = by_cat.get(cat, [])
        if not items:
            continue
        out += [f"## {cat}", ""]
        if cat == "Q&A":
            claimed = set()
            for _label, pattern, heading, blurb in PREFIX_GROUPS:
                group = [n for n in items if pattern.match(n["title"])]
                if not group:
                    continue
                claimed |= {n["number"] for n in group}
                out += [f"### {heading}", "", blurb, "",
                        "| Thread | Depth |", "|---|---|"]
                out += [row(n) for n in sorted(group, key=lambda x: x["title"])]
                out.append("")
            rest = [n for n in items if n["number"] not in claimed]
            if rest:
                out += ["### Everything else", "", "| Thread | Depth |", "|---|---|"]
                out += [row(n) for n in rest]
                out.append("")
        else:
            out += ["| Thread | Depth |", "|---|---|"]
            out += [row(n) for n in items]
            out.append("")

    out += ["---", "",
            "**✅ marks a thread with an accepted answer.** Those are harvested weekly into",
            "[the FAQ](../90-reference/faq.md), which links rather than copies — the thread",
            "carries the argument that got there, and that is usually the more useful half.", ""]
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    content = render(fetch())
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != content:
            print("discussion-map.md is out of date; run scripts/discussion_map.py")
            return 1
        print("discussion-map.md is up to date")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(content, encoding="utf-8")
    print(f"wrote {OUT.relative_to(OUT.parent.parent.parent)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
